apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-deployment
  namespace: apps
  labels:
    app: personal-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site-container
          image: ghcr.io/nkdem/personal-site:8ee7220764e8bd97af09c7175e4551585db8bf71
          ports:
            - containerPort: 80
