apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-deployment
  namespace: apps
  labels:
    app: personal-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site-container
          image: ghcr.io/nkdem/personal-site:94f44aea4461847793330ba9c0afc3fa2e0ea5ef
          ports:
            - containerPort: 80
