apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-deployment
  namespace: apps
  labels:
    app: personal-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site-container
          image: ghcr.io/nkdem/personal-site:73334bfd176b8203a44208f5b389b9fd93308169
          ports:
            - containerPort: 80
