apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-deployment
  namespace: apps
  labels:
    app: personal-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site-container
          image: ghcr.io/nkdem/personal-site:13eb8d474e2f3ea3f40aa6e469afe4b3e22862f8
          ports:
            - containerPort: 80
