# service.yaml (ClusterIP version for use with Ingress)
apiVersion: v1
kind: Service
metadata:
  name: personal-site-service
  namespace: apps 
  labels:
    app: personal-site
spec:
  selector:
    app: personal-site
  ports:
    - protocol: TCP
      port: 80      # Service internal port
      targetPort: 80 # Pod target port
  type: ClusterIP # Accessible only from inside the cluster
